_target_: lloca.framesnet.equi_frames.LearnedSO3Frames
is_global: false
random: false
fix_params: false
compile: false
ortho_kwargs:
 use_float64: true
 method: gramschmidt
 eps_norm: 1e-10
 eps_reg: 1e-16
 eps_reg_lightlike: 1e-16
 checks: true

defaults:
 - equivectors: equimlp
