_target_: experiments.amplitudes.wrappers.DSIWrapper
particle_type: null
network_float64: null

net:
 _target_: experiments.baselines.dsi.DSI

 use_deepset: false
 sum_deepset: true
 use_invariants: true
 type_token_list: null

 hidden_channels_prenet: 128
 hidden_layers_prenet: 4
 out_dim_prenet_sep: 64
 hidden_channels_net: 128
 hidden_layers_net: 4
 
defaults:
 - framesnet: identity
