_target_: experiments.tagging.wrappers.LGATrWrapper
mean_aggregation: false
out_channels: null
use_amp: false

net:
 _target_: lgatr.LGATr
 _partial_: true

 in_mv_channels: 1
 in_s_channels: null
 out_mv_channels: null
 out_s_channels: null
 hidden_mv_channels: 2
 hidden_s_channels: 4

 num_blocks: 1
 attention:
  num_heads: 2
  multi_query: false
  increase_hidden_channels: 1
  head_scale: true
 mlp:
  activation: gelu
  increase_hidden_channels: 2

defaults:
 - framesnet: identity
